# Generated by Django 3.2.7 on 2021-09-03 05:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210830_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_long_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
