# Generated by Django 3.2.7 on 2021-09-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210903_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
