# Generated by Django 3.2.7 on 2021-09-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_subcategories_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_by_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.merchantuser'),
        ),
    ]
