# Generated by Django 3.2.7 on 2021-09-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210907_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='is_active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.CharField(blank=True, default='5', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customeruser'),
        ),
    ]
