# Generated by Django 3.2.7 on 2021-09-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210907_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainapp.productreviews'),
        ),
    ]
