# Generated by Django 3.2.7 on 2021-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_productreviews_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=-1.0),
            preserve_default=False,
        ),
    ]
