# Generated by Django 3.2.7 on 2021-09-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_productreviews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
